version: '3.2'

services:
  mid-server:
    image: mid-server-london
    build: mid-server/.
    environment:
      SN_URL: dev00000
      SN_USER: admin
      SN_PASSWD: '**********'
      SN_MID_NAME: mid-docker-02
    volumes: 
      - "./logs:/opt/agent/logs"
    networks:
      - backend

  cicd:
    image: sn-cicd-example-v3
    build: .
    env_file: .env
    ports:
      - 8080:8080
      - 8443:8443
    volumes: 
      - "./root:/opt/cicd"
      # dont use this in prod
      - "/Users/user/.ssh:/home/node/.ssh"
    networks:
      - backend

networks:
  backend:
